version: "1"

services:
  - type: web
    name: kmedya
    runtime: python
    repo: https://github.com/kmedya-dev/my-portfolio
    region: singapore
    plan: free
    rootDir: my_portfolio-fullstack/
    buildCommand: ./build.sh
    startCommand: gunicorn my_portfolio_backend.wsgi:application
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres@my_portfolio-fullstack
          property: connectionString

databases:
  - name: postgres@my_portfolio-fullstack
    databaseName: my_portfolio_fullstack_db
    user: kmedya
    plan: free
    region: singapore
    postgresMajorVersion: "16"
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
