# Generated by Django 5.2.4 on 2026-05-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
    ]
