# Generated by Django 5.2.4 on 2025-07-25 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('src', models.URLField(blank=True, help_text='Paste a public URL (GitHub Gist, YouTube, news article, etc.) to fetch content.', null=True, verbose_name='Source URL')),
                ('content_manual', models.TextField(blank=True, help_text='Manually written content for the blog post.', null=True, verbose_name='Manual Content')),
                ('content_fetched', models.TextField(blank=True, help_text='Content automatically fetched from the Source URL. This field is read-only.', null=True, verbose_name='Fetched Content')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit', models.CharField(blank=True, help_text='Optional: Credit the original source (e.g., author name, link).', max_length=255, null=True, verbose_name='Credit/Attribution')),
                ('show_fetched_first', models.BooleanField(default=False, help_text='Check to display fetched content before manual content on detail page.', verbose_name='Show Fetched Content First')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-pub_date'],
            },
        ),
    ]
