# Generated by Django 5.2.4 on 2026-05-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_image_project_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                blank=True, help_text="Comma-separated technologies", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                blank=True, help_text="GitHub Repository Link", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, help_text="Live Demo Link", null=True),
        ),
    ]
