databases:
  - name: postgres
    databaseName: my_portfolio_db
    user: my_portfolio_user

services:
  - type: web
    name: my-portfolio
    runtime: python
    pythonVersion: "3.12.11"
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_portfolio_backend.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4