services:
- type: web
  name: kmedya
  runtime: python
  repo: https://github.com/kmedya-dev/my-portfolio
  branch: full-stack
  plan: free
  region: singapore
  buildCommand: ./build.sh
  startCommand: gunicorn my_portfolio_backend.wsgi
  healthCheckPath: /helthz
  autoDeployTrigger: commit
  rootDir: my_portfolio-fullstack/
  previews:
    generation: manual
version: "1"